gateways:
  local:
    connection:
      type: postgres
      database: postgres
      port: 5432
      host: 127.0.0.1
      user: postgres
      password: postgres
default_gateway: local

model_defaults:
  dialect: postgres

cicd_bot:
    type: github
    merge_method: squash
    enable_deploy_command: true
    auto_categorize_changes:
      external: full
      python: full
      sql: full
      seed: full

plan:
  enable_preview: true
